name: Continuous Integration

on:
  push:
    branches: [ main ]      # run on every push to main
  pull_request:
    branches: [ main ]      # run for PRs targeting main
  workflow_dispatch:         # allow manual runs in GitHub UI

jobs:
  build-and-test:
    runs-on: ubuntu-latest   # Linux VM runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci || npm install

      - name: Lint (optional)
        run: npm run lint

      - name: Run tests
        run: npm test
